apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: photouploader
  namespace: nginx-mra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-mra
        component: photouploader
    spec:
      imagePullSecrets:
        - name: <DOCKER_SECRET>
      containers:
      - name: photouploader
        image: <IMAGE_REPO_AND_TAG>
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https
        env:
          - name: ALBUM_MANAGER_URL
            value: "http://localhost/album-manager"
          - name: AWS_ACCESS_KEY_ID
            value: <AWS_ACCESS_KEY_ID>
          - name: AWS_REGION
            value: us-west-1
          - name: AWS_SECRET_ACCESS_KEY
            value: <AWS_SECRET_ACCESS_KEY>
          - name: RESIZER_URL
            value: "http://localhost/resizer/v1/image"
          - name: S3_BUCKET
            value: <S3_BUCKET>
          - name: S3_URL
            value: "<S3_URL>"
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /status
            port: 443
            httpHeaders:
              - name: Host
                value: <K8S_HOST_NAME>
          periodSeconds: 20
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 10
